// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqKyg1EtTKVagex1TYQg1wLih7bnN4dK4',
    appId: '1:934404827979:web:90f5dd90f716333ac3d6ce',
    messagingSenderId: '934404827979',
    projectId: 'phishguard-38c10',
    authDomain: 'phishguard-38c10.firebaseapp.com',
    storageBucket: 'phishguard-38c10.firebasestorage.app',
    measurementId: 'G-FPMLNMFTYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpQHEWHzHZMC-JDakrdBi1lweMTS5bY7Q',
    appId: '1:934404827979:android:8c92050942c5c85ac3d6ce',
    messagingSenderId: '934404827979',
    projectId: 'phishguard-38c10',
    storageBucket: 'phishguard-38c10.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqKyg1EtTKVagex1TYQg1wLih7bnN4dK4',
    appId: '1:934404827979:web:c5fc5696dc18d80bc3d6ce',
    messagingSenderId: '934404827979',
    projectId: 'phishguard-38c10',
    authDomain: 'phishguard-38c10.firebaseapp.com',
    storageBucket: 'phishguard-38c10.firebasestorage.app',
    measurementId: 'G-PHNJL9RM51',
  );
}
